# Generated by Django 6.0.2 on 2026-03-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfl_updates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrivalrecord',
            name='delay_seconds',
        ),
        migrations.RemoveField(
            model_name='arrivalrecord',
            name='scheduled_time',
        ),
    ]
